import { Link } from "react-router-dom";
import { AccordionContent, AccordionItem, AccordionTrigger } from "../ui/accordion";
import { LuPieChart } from "react-icons/lu";
export function AdminNavHome() {
    return (
        <AccordionItem value="item-1">
            <AccordionTrigger>
                <div className='flex items-center gap-3'>
                    <LuPieChart className="text-[#464F66] w-[16px] h-[16px] ml-[1px]"/>
                    <h2>Home</h2>
                </div>
            </AccordionTrigger>
            <AccordionContent>
                <ul className='w-[75%] mx-auto text-start pl-3 mt-1'>
                    <li className='hover:bg-gray-100 rounded-md text-[13px] p-1.5 px-3'>E commerce</li>
                    <li className='hover:bg-gray-100 rounded-md text-[13px] p-1.5 px-3'>Project management</li>
                    <li className='hover:bg-gray-100 rounded-md text-[13px] p-1.5 px-3'>CRM</li>
                </ul>
            </AccordionContent>
        </AccordionItem>
    )
}

// --fa-font-solid: normal 900 1em/1 "Font Awesome 6 Solid";
// --fa-font-regular: normal 400 1em/1 "Font Awesome 6 Regular";
// --fa-font-light: normal 300 1em/1 "Font Awesome 6 Light";
// --fa-font-thin: normal 100 1em/1 "Font Awesome 6 Thin";
// --fa-font-duotone: normal 900 1em/1 "Font Awesome 6 Duotone";
// --fa-font-sharp-solid: normal 900 1em/1 "Font Awesome 6 Sharp";
// --fa-font-sharp-regular: normal 400 1em/1 "Font Awesome 6 Sharp";
// --fa-font-sharp-light: normal 300 1em/1 "Font Awesome 6 Sharp";
// --fa-font-brands: normal 400 1em/1 "Font Awesome 6 Brands";
// --fc-small-font-size: .85em;
// --fc-page-bg-color: #fff;
// --fc-neutral-bg-color: hsla(0,0%,82%,.3);
// --fc-neutral-text-color: grey;
// --fc-border-color: #ddd;
// --fc-button-text-color: #fff;
// --fc-button-bg-color: #2c3e50;
// --fc-button-border-color: #2c3e50;
// --fc-button-hover-bg-color: #1e2b37;
// --fc-button-hover-border-color: #1a252f;
// --fc-button-active-bg-color: #1a252f;
// --fc-button-active-border-color: #151e27;
// --fc-event-bg-color: #3788d8;
// --fc-event-border-color: #3788d8;
// --fc-event-text-color: #fff;
// --fc-event-selected-overlay-color: rgba(0,0,0,.25);
// --fc-more-link-bg-color: #d0d0d0;
// --fc-more-link-text-color: inherit;
// --fc-event-resizer-thickness: 8px;
// --fc-event-resizer-dot-total-width: 8px;
// --fc-event-resizer-dot-border-width: 1px;
// --fc-non-business-color: hsla(0,0%,84%,.3);
// --fc-bg-event-color: #8fdf82;
// --fc-bg-event-opacity: 0.3;
// --fc-highlight-color: rgba(188,232,241,.3);
// --fc-today-bg-color: rgba(255,220,40,.15);
// --fc-now-indicator-color: red;
// --fc-daygrid-event-dot-width: 8px;
// --swiper-theme-color: #007aff;
// --phoenix-blue: #3874ff;
// --phoenix-indigo: #6610f2;
// --phoenix-purple: #6f42c1;
// --phoenix-pink: #d63384;
// --phoenix-red: #EC1F00;
// --phoenix-orange: #E5780B;
// --phoenix-yellow: #ffc107;
// --phoenix-green: #25b003;
// --phoenix-teal: #20c997;
// --phoenix-cyan: #0097eb;
// --phoenix-black: #000000;
// --phoenix-white: #fff;
// --phoenix-gray: #6e7891;
// --phoenix-gray-dark: #141824;
// --phoenix-gray-50: #f5f7fa;
// --phoenix-gray-100: #eff2f6;
// --phoenix-gray-200: #e3e6ed;
// --phoenix-gray-300: #cbd0dd;
// --phoenix-gray-400: #9fa6bc;
// --phoenix-gray-500: #8a94ad;
// --phoenix-gray-600: #6e7891;
// --phoenix-gray-700: #525b75;
// --phoenix-gray-800: #3e465b;
// --phoenix-gray-900: #31374a;
// --phoenix-gray-1000: #222834;
// --phoenix-gray-1100: #141824;
// --phoenix-primary: #3874ff;
// --phoenix-secondary: #31374a;
// --phoenix-success: #25b003;
// --phoenix-info: #0097eb;
// --phoenix-warning: #E5780B;
// --phoenix-danger: #EC1F00;
// --phoenix-light: #eff2f6;
// --phoenix-dark: #141824;
// --phoenix-primary-rgb: 56, 116, 255;
// --phoenix-secondary-rgb: 49, 55, 74;
// --phoenix-success-rgb: 37, 176, 3;
// --phoenix-info-rgb: 0, 151, 235;
// --phoenix-warning-rgb: 229, 120, 11;
// --phoenix-danger-rgb: 236, 31, 0;
// --phoenix-light-rgb: 239, 242, 246;
// --phoenix-dark-rgb: 20, 24, 36;
// --phoenix-primary-text-emphasis: #003CC7;
// --phoenix-secondary-text-emphasis: #525b75;
// --phoenix-success-text-emphasis: #1C6C09;
// --phoenix-info-text-emphasis: #005585;
// --phoenix-warning-text-emphasis: #BC3803;
// --phoenix-danger-text-emphasis: #B81800;
// --phoenix-light-text-emphasis: #141824;
// --phoenix-dark-text-emphasis: #fff;
// --phoenix-primary-bg-subtle: #E5EDFF;
// --phoenix-secondary-bg-subtle: #eff2f6;
// --phoenix-success-bg-subtle: #D9FBD0;
// --phoenix-info-bg-subtle: #C7EBFF;
// --phoenix-warning-bg-subtle: #FFEFCA;
// --phoenix-danger-bg-subtle: #FFE0DB;
// --phoenix-light-bg-subtle: #f7f9fb;
// --phoenix-dark-bg-subtle: #9fa6bc;
// --phoenix-primary-border-subtle: #85A9FF;
// --phoenix-secondary-border-subtle: #cbd0dd;
// --phoenix-success-border-subtle: #90D67F;
// --phoenix-info-border-subtle: #60C6FF;
// --phoenix-warning-border-subtle: #FFCC85;
// --phoenix-danger-border-subtle: #F48270;
// --phoenix-light-border-subtle: #eff2f6;
// --phoenix-dark-border-subtle: #8a94ad;
// --phoenix-white-rgb: 255, 255, 255;
// --phoenix-black-rgb: 0, 0, 0;
// --phoenix-font-sans-serif: "Nunito Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
// --phoenix-font-monospace: "SFMono-Regular", Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
// --phoenix-gradient: linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0));
// --phoenix-body-font-family: var(--phoenix-font-sans-serif);
// --phoenix-body-font-size: 1rem;
// --phoenix-body-font-weight: 400;
// --phoenix-body-line-height: 1.49;
// --phoenix-body-color: #31374a;
// --phoenix-body-color-rgb: 49, 55, 74;
// --phoenix-body-bg: #f5f7fa;
// --phoenix-body-bg-rgb: 245, 247, 250;
// --phoenix-emphasis-color: #141824;
// --phoenix-emphasis-color-rgb: 20, 24, 36;
// --phoenix-secondary-color: #3e465b;
// --phoenix-secondary-color-rgb: 62, 70, 91;
// --phoenix-secondary-bg: #e3e6ed;
// --phoenix-secondary-bg-rgb: 227, 230, 237;
// --phoenix-tertiary-color: #525b75;
// --phoenix-tertiary-color-rgb: 82, 91, 117;
// --phoenix-tertiary-bg: #cbd0dd;
// --phoenix-tertiary-bg-rgb: 203, 208, 221;
// --phoenix-heading-color: var(--phoenix-emphasis-color);
// --phoenix-link-color: #3874ff;
// --phoenix-link-color-rgb: 56, 116, 255;
// --phoenix-link-decoration: none;
// --phoenix-link-hover-color: #003CC7;
// --phoenix-link-hover-color-rgb: 0, 60, 199;
// --phoenix-link-hover-decoration: underline;
// --phoenix-code-color: #D6630A;
// --phoenix-highlight-color: #31374a;
// --phoenix-highlight-bg: #fff3cd;
// --phoenix-border-width: 1px;
// --phoenix-border-style: solid;
// --phoenix-border-color: #cbd0dd;
// --phoenix-border-color-translucent: rgba(203, 208, 221, 0.54);
// --phoenix-border-radius: 0.375rem;
// --phoenix-border-radius-sm: 0.25rem;
// --phoenix-border-radius-lg: 0.5rem;
// --phoenix-border-radius-xl: 1rem;
// --phoenix-border-radius-xxl: 2rem;
// --phoenix-border-radius-2xl: var(--phoenix-border-radius-xxl);
// --phoenix-border-radius-pill: 50rem;
// --phoenix-box-shadow: 0px 2px 4px -2px rgba(36, 40, 46, 0.08);
// --phoenix-box-shadow-sm: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075);
// --phoenix-box-shadow-lg: 0 1rem 3rem rgba(0, 0, 0, 0.175);
// --phoenix-box-shadow-inset: inset 0 1px 2px rgba(0, 0, 0, 0.075);
// --phoenix-focus-ring-width: 0.25rem;
// --phoenix-focus-ring-opacity: 0.25;
// --phoenix-focus-ring-color: rgba(56, 116, 255, 0.25);
// --phoenix-form-valid-color: #25b003;
// --phoenix-form-valid-border-color: #25b003;
// --phoenix-form-invalid-color: #EC1F00;
// --phoenix-form-invalid-border-color: #EC1F00;
// --phoenix-scroll-margin-top: 2.5rem;
// --phoenix-navbar-top-height: 4rem;
// --phoenix-navbar-top-menu-margin: 1.5rem;
// --phoenix-gray-50-rgb: 245, 247, 250;
// --phoenix-gray-100-rgb: 239, 242, 246;
// --phoenix-gray-200-rgb: 227, 230, 237;
// --phoenix-gray-300-rgb: 203, 208, 221;
// --phoenix-gray-400-rgb: 159, 166, 188;
// --phoenix-gray-500-rgb: 138, 148, 173;
// --phoenix-gray-600-rgb: 110, 120, 145;
// --phoenix-gray-700-rgb: 82, 91, 117;
// --phoenix-gray-800-rgb: 62, 70, 91;
// --phoenix-gray-900-rgb: 49, 55, 74;
// --phoenix-gray-1000-rgb: 34, 40, 52;
// --phoenix-gray-1100-rgb: 20, 24, 36;
// --phoenix-primary-lighter: #ADC5FF;
// --phoenix-primary-light: #85A9FF;
// --phoenix-primary-dark: #004DFF;
// --phoenix-primary-darker: #003CC7;
// --phoenix-secondary-lighter: #e3e6ed;
// --phoenix-secondary-light: #cbd0dd;
// --phoenix-secondary-dark: #222834;
// --phoenix-secondary-darker: #525b75;
// --phoenix-warning-lighter: #FFE6AD;
// --phoenix-warning-light: #FFCC85;
// --phoenix-warning-dark: #D6630A;
// --phoenix-warning-darker: #BC3803;
// --phoenix-danger-lighter: #FABCB3;
// --phoenix-danger-light: #F48270;
// --phoenix-danger-dark: #CC1B00;
// --phoenix-danger-darker: #B81800;
// --phoenix-success-lighter: #BEE8B4;
// --phoenix-success-light: #90D67F;
// --phoenix-success-dark: #23890B;
// --phoenix-success-darker: #1C6C09;
// --phoenix-info-lighter: #96D9FF;
// --phoenix-info-light: #60C6FF;
// --phoenix-info-dark: #0080C7;
// --phoenix-info-darker: #005585;
// --phoenix-primary-lighter-rgb: 173, 197, 255;
// --phoenix-primary-light-rgb: 133, 169, 255;
// --phoenix-primary-dark-rgb: 0, 77, 255;
// --phoenix-primary-darker-rgb: 0, 60, 199;
// --phoenix-secondary-lighter-rgb: 227, 230, 237;
// --phoenix-secondary-light-rgb: 203, 208, 221;
// --phoenix-secondary-dark-rgb: 34, 40, 52;
// --phoenix-secondary-darker-rgb: 82, 91, 117;
// --phoenix-warning-lighter-rgb: 255, 230, 173;
// --phoenix-warning-light-rgb: 255, 204, 133;
// --phoenix-warning-dark-rgb: 214, 99, 10;
// --phoenix-warning-darker-rgb: 188, 56, 3;
// --phoenix-danger-lighter-rgb: 250, 188, 179;
// --phoenix-danger-light-rgb: 244, 130, 112;
// --phoenix-danger-dark-rgb: 204, 27, 0;
// --phoenix-danger-darker-rgb: 184, 24, 0;
// --phoenix-success-lighter-rgb: 190, 232, 180;
// --phoenix-success-light-rgb: 144, 214, 127;
// --phoenix-success-dark-rgb: 35, 137, 11;
// --phoenix-success-darker-rgb: 28, 108, 9;
// --phoenix-info-lighter-rgb: 150, 217, 255;
// --phoenix-info-light-rgb: 96, 198, 255;
// --phoenix-info-dark-rgb: 0, 128, 199;
// --phoenix-info-darker-rgb: 0, 85, 133;
// --phoenix-quaternary-color: #8a94ad;
// --phoenix-quaternary-color-rgb: 138, 148, 173;
// --phoenix-quaternary-bg: #9fa6bc;
// --phoenix-quaternary-bg-rgb: 159, 166, 188;
// --phoenix-emphasis-bg: #fff;
// --phoenix-emphasis-bg-rgb: 255, 255, 255;
// --phoenix-body-highlight-color: #222834;
// --phoenix-body-highlight-color-rgb: 34, 40, 52;
// --phoenix-body-highlight-bg: #eff2f6;
// --phoenix-body-highlight-bg-rgb: 239, 242, 246;
// --phoenix-border-color-rgb: 203, 208, 221;
// --phoenix-border-color-translucent-rgb: 203, 208, 221;
// --phoenix-input-group-addon-bg-global: #eff2f6;
// --phoenix-dropdown-link-color-global: #525b75;
// --phoenix-dropdown-link-hover-color-global: #292e3b;
// --phoenix-nav-vertical-color-global: #141824;
// --phoenix-scrollbar-bg: rgba(var(--phoenix-quaternary-bg-rgb), 0.55);
// --phoenix-docs-language-bg: #222834;
// --phoenix-navbar-top-link-color: var(--phoenix-body-color);
// --phoenix-navbar-top-menu-bg-color: var(--phoenix-emphasis-bg);
// --phoenix-navbar-top-border-color: #cbd0dd;
// --phoenix-navbar-top-link-hover-color: var(--phoenix-body-highlight-color);
// --phoenix-navbar-top-link-hover-bg: var(--phoenix-body-highlight-bg);
// --phoenix-navbar-top-link-active-color: var(--phoenix-primary);
// --phoenix-navbar-top-dropdown-color: var(--phoenix-body-color);
// --phoenix-navbar-top-dropdown-hover-bg: var(--phoenix-body-highlight-bg);
// --phoenix-dual-nav-border-color: #e3e6ed;
// --phoenix-dual-nav-first-layer-bg: #eff2f6;
// --phoenix-navbar-vertical-border-color: #cbd0dd;
// --phoenix-navbar-vertical-bg-color: var(--phoenix-emphasis-bg);
// --phoenix-navbar-vertical-label-color: #6e7891;
// --phoenix-navbar-vertical-link-color: #525b75;
// --phoenix-navbar-vertical-link-hover-color: #3e465b;
// --phoenix-navbar-vertical-link-hover-bg: #eff2f6;
// --phoenix-navbar-vertical-link-active-color: #3874ff;
// --phoenix-navbar-vertical-link-disable-color: #8a94ad;
// --phoenix-navbar-vertical-width: 15.875rem;
// --phoenix-navbar-vertical-dropdown-indicator-color: #8a94ad;
// --phoenix-navbar-footer-border-color: var(--phoenix-border-color);
// --phoenix-navbar-vertical-hr-color: #e3e6ed;
// --phoenix-navbar-vertical-collapsed-menu-bg: #fff;
// --phoenix-hamburger-menu-color: #6e7891;
// --phoenix-navbar-top-bg-color: var(--phoenix-emphasis-bg);
// --phoenix-btn-hover-border-color: transparent;
// --phoenix-btn-active-border-color: transparent;
// --phoenix-choices-inner-min-height: auto;
// --phoenix-choices-item-has-no-choices-bg: var(--phoenix-emphasis-bg);
// --phoenix-flatpickr-calendar-input-bg: var(--phoenix-emphasis-bg);
// --phoenix-flatpickr-calendar-bg: #e3e6ed;
// --phoenix-flatpickr-current-month-color: #31374a;
// --phoenix-flatpickr-weekday-color: #31374a;
// --phoenix-flatpickr-calendar-day-hover-bg: rgba(var(--phoenix-tertiary-bg-rgb), 0.5);
// --phoenix-flatpickr-weekend-days-color: #E5780B;
// --phoenix-flatpickr-today-color: #fff;
// --phoenix-flatpickr-calendar-day-selected-bg: rgba(var(--phoenix-primary-rgb), 0.2);
// --phoenix-calendar-bg: #e3e6ed;
// --phoenix-calendar-border-color: var(--phoenix-body-bg);
// --phoenix-theme-wizard-nav-item-circle-bg: var(--phoenix-body-highlight-bg);
// --phoenix-theme-wizard-complete-color: #25b003;
// --phoenix-theme-wizard-active-color: #3874ff;
// --phoenix-tinymce-bg: var(--phoenix-emphasis-bg);
// --phoenix-tinymce-tox-tbtn-enabled-icon-color: var(--phoenix-secondary-color);
// --phoenix-choices-item-bg: var(--phoenix-primary-bg-subtle);
// --phoenix-choices-item-color: var(--phoenix-body-highlight-color);
// --phoenix-avatar-name-color: var(--phoenix-primary-dark);
// --phoenix-logo-text: rgba(var(--phoenix-tertiary-color-rgb),0.8);
// --phoenix-theme-control-toggle-bg: rgba(255, 204, 133, 0.24);
// --phoenix-theme-control-toggle-hover-bg: var(--phoenix-warning);
// --phoenix-theme-control-toggle-color: var(--phoenix-warning);
// --phoenix-theme-control-toggle-hover-color: #FFEFCA;
// --phoenix-kanban-bg: #e3e6ed;
// --phoenix-kanban-column-bg: var(--phoenix-body-bg);
// --phoenix-kanban-ghost-bg: var(--phoenix-body-highlight-bg);
// --phoenix-kanban-drag-bg: var(--phoenix-white);
// --phoenix-kanban-column-hover-bg: var(--phoenix-white);
// --phoenix-leaflet-bar-bg: var(--phoenix-body-highlight-bg);
// --phoenix-leaflet-popup-content-wrapper-bg: #fff;
// --phoenix-breakpoint-xs: 0;
// --phoenix-breakpoint-sm: 576px;
// --phoenix-breakpoint-md: 768px;
// --phoenix-breakpoint-lg: 992px;
// --phoenix-breakpoint-xl: 1200px;
// --phoenix-breakpoint-xxl: 1540px;
// --phoenix-footer-height: 4rem;
// text-align: var(--phoenix-body-text-align);
// -webkit-text-size-adjust: 100%;
// -webkit-tap-highlight-color: rgba(0,0,0,0);
// -webkit-font-smoothing: antialiased;
// --phoenix-gutter-x: 2rem;
// --phoenix-gutter-y: 0;
// --phoenix-navbar-padding-x: 1.5rem;
// --phoenix-navbar-padding-y: 0.5rem;
// --phoenix-navbar-color: rgba(var(--phoenix-emphasis-color-rgb), 0.65);
// --phoenix-navbar-hover-color: rgba(var(--phoenix-emphasis-color-rgb), 0.9);
// --phoenix-navbar-disabled-color: rgba(var(--phoenix-emphasis-color-rgb), 0.25);
// --phoenix-navbar-active-color: rgba(var(--phoenix-emphasis-color-rgb), 1);
// --phoenix-navbar-brand-padding-y: -0.210078125rem;
// --phoenix-navbar-brand-margin-end: 1rem;
// --phoenix-navbar-brand-font-size: 1.953125rem;
// --phoenix-navbar-brand-color: rgba(var(--phoenix-emphasis-color-rgb), 1);
// --phoenix-navbar-brand-hover-color: rgba(var(--phoenix-emphasis-color-rgb), 1);
// --phoenix-navbar-nav-link-padding-x: 0.5rem;
// --phoenix-navbar-toggler-padding-y: 0.25rem;
// --phoenix-navbar-toggler-padding-x: 0.75rem;
// --phoenix-navbar-toggler-font-size: 1.2rem;
// --phoenix-navbar-toggler-icon-bg: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='%239da9bb' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M0 6h30M0 14h30M0 22h30'/%3E%3C/svg%3E");
// --phoenix-navbar-toggler-border-color: rgba(var(--phoenix-emphasis-color-rgb), 0.15);
// --phoenix-navbar-toggler-border-radius: 0.375rem;
// --phoenix-navbar-toggler-focus-width: 0;
// --phoenix-navbar-toggler-transition: box-shadow 0.15s ease-in-out;
// font-family: var(--phoenix-font-sans-serif);
// --phoenix-nav-link-padding-x: 0;
// --phoenix-nav-link-padding-y: 0.5rem;
// --phoenix-nav-link-font-weight: ;
// --phoenix-nav-link-color: var(--phoenix-navbar-color);
// --phoenix-nav-link-hover-color: var(--phoenix-navbar-hover-color);
// --phoenix-nav-link-disabled-color: var(--phoenix-navbar-disabled-color);
// list-style: none;
// cursor: pointer;
// font-size: var(--phoenix-nav-link-font-size);
// font-weight: var(--phoenix-nav-link-font-weight);
// word-break: break-word;
// line-height: 1.188rem;
// white-space: nowrap;
// color: var(--phoenix-navbar-vertical-link-color);
// box-sizing: border-box;
// padding-top: .125rem;
// <span class="nav-link-text" style="">Home</span>